create table DATA_DICT
(
	CODE VARCHAR2(255 char) not null,
	TYPE_ID VARCHAR2(255 char) not null,
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(255 char),
	primary key (CODE, TYPE_ID)
)
/

create table UMS_ACL
(
	ID VARCHAR2(32 char) not null
		primary key,
	ACLSTATE NUMBER(10),
	PID VARCHAR2(255 char),
	PTYPE VARCHAR2(255 char),
	RTYPE VARCHAR2(255 char),
	RID VARCHAR2(255 char)
)
/

create table UMS_APPLICATION
(
	ID VARCHAR2(32 char) not null
		primary key,
	DESCRIPTION VARCHAR2(255 char),
	NAME VARCHAR2(255 char),
	SN VARCHAR2(255 char),
	SSOFLAG NUMBER(5),
	URL VARCHAR2(255 char)
)
/

create table UMS_BUTTON
(
	ID VARCHAR2(32 char) not null
		primary key,
	BUTTON_EVENT VARCHAR2(255 char),
	BUTTON_ICON VARCHAR2(255 char),
	BUTTON_NAME VARCHAR2(255 char),
	BUTTON_ORDER NUMBER(10),
	DESCRIPTION VARCHAR2(255 char),
	IS_AVAILABLE NUMBER(5)
)
/

create table UMS_DEPARTMENT
(
	ID VARCHAR2(32 char) not null
		primary key,
	DESCRIPTION VARCHAR2(255 char),
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(255 char),
	ORG_ID VARCHAR2(32),
	ORGID VARCHAR2(255)
)
/

create table UMS_MENU_BUTTON
(
	ID VARCHAR2(32 char) not null
		primary key,
	BUTTON_ID VARCHAR2(255 char),
	MENU_ID VARCHAR2(255 char)
)
/

create table UMS_USER_DEPARTMENT_RELATION
(
	ID VARCHAR2(32 char) not null
		primary key,
	DEPARTMENT_ID VARCHAR2(32 char)
		constraint FKMIKBBFLJT1R5R0L1MPHUR3BUP
			references UMS_DEPARTMENT,
	USER_ID VARCHAR2(32 char)
)
/

create table UMS_ORG_RULE
(
	ID VARCHAR2(32 char) not null
		primary key,
	MANAGER_ORG VARCHAR2(255 char),
	ORG_ID VARCHAR2(255 char)
)
/

create table UMS_ORG_TYPE
(
	ID VARCHAR2(32 char) not null
		primary key,
	NAME VARCHAR2(255 char),
	SN VARCHAR2(255 char)
)
/

create table UMS_ORG_TYPE_RULE
(
	ID VARCHAR2(32 char) not null
		primary key,
	CID VARCHAR2(255 char),
	NUM NUMBER(10),
	PID VARCHAR2(255 char)
)
/

create table UMS_PERSON
(
	ID VARCHAR2(255 char) not null
		primary key,
	BIRTH TIMESTAMP(6),
	NAME VARCHAR2(255 char),
	PHONE VARCHAR2(255 char),
	SEX NUMBER(5),
	SFZH VARCHAR2(255 char),
	SN VARCHAR2(50)
)
/

create table UMS_POSITION
(
	ID VARCHAR2(32 char) not null
		primary key,
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(255 char),
	SN VARCHAR2(255 char),
	DEPARTMENT_ID VARCHAR2(32),
	ORG_ID VARCHAR2(32),
	GROUP_ID VARCHAR2(255)
)
/

create table UMS_ROLE
(
	ID VARCHAR2(32 char) not null
		primary key,
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(255 char),
	SN VARCHAR2(255 char),
	APP_ID VARCHAR2(32)
)
/

create table UMS_USER
(
	ID VARCHAR2(32 char) not null
		primary key,
	CREATE_DATE TIMESTAMP(6),
	DELETED NUMBER(5),
	IS_AVAILABLE NUMBER(5),
	NICKNAME VARCHAR2(255 char),
	PASSWORD VARCHAR2(255 char),
	SALT VARCHAR2(255 char),
	USERNAME VARCHAR2(255 char),
	EMAIL VARCHAR2(255),
	OFPW VARCHAR2(255)
)
/

alter table UMS_USER_DEPARTMENT_RELATION
	add constraint FK3UAL015I5AQ4GF9DRTJ7IG4FG
		foreign key (USER_ID) references UMS_USER
/

create table UMS_USER_ORG_DEPARTMENT_POS
(
	ID VARCHAR2(32 char) not null
		primary key,
	ORGID VARCHAR2(255 char),
	POSID VARCHAR2(255 char),
	USERID VARCHAR2(255 char),
	DEPARTMENTID VARCHAR2(32)
)
/

create table UMS_USER_ROLE_RELATION
(
	ID VARCHAR2(32 char) not null
		primary key,
	ROLE_ID VARCHAR2(32 char)
		constraint FK6DUI3P07CW55NS2BFWD47RHCU
			references UMS_ROLE,
	USER_ID VARCHAR2(32 char)
		constraint FK9FRV941FTDM8V9PCKLMD1MVJB
			references UMS_USER
)
/

create table UMS_CONTROLLER_RESOURCES
(
	ID VARCHAR2(32 char) not null
		primary key,
	CONTROLLER_NAME VARCHAR2(255 char),
	CONTROLLER_ORDER NUMBER(10),
	CONTROLLER_SN VARCHAR2(255 char),
	CONTROLLER_URL_MAPPING VARCHAR2(255 char),
	IS_AVAILABLE NUMBER(5),
	APPLICATION_ID VARCHAR2(32 char)
		constraint FKKE0L3B4MTUDPS8YLBL2EEV3LQ
			references UMS_APPLICATION,
	PARENT_ID VARCHAR2(32 char)
		constraint FK3O9FR2TBLW30MQ27JK4NTREJO
			references UMS_CONTROLLER_RESOURCES,
	MENU_ID VARCHAR2(32)
)
/

create table UMS_MENU_RESOURCE
(
	ID VARCHAR2(32 char) not null
		primary key,
	IS_AVAILABLE NUMBER(5),
	IS_LEAF NUMBER(5),
	MENU_ICON VARCHAR2(255 char),
	MENU_NAME VARCHAR2(255 char),
	MENU_ORDER NUMBER(10),
	MENU_SN VARCHAR2(255 char),
	MENU_URL VARCHAR2(255 char),
	APPLICATION_ID VARCHAR2(32 char)
		constraint FKC6L486MLI6EJOID8NMCU1XL51
			references UMS_APPLICATION,
	PARENT_ID VARCHAR2(32 char)
		constraint FKCYVEYOFORFUFP944EE0OSA79V
			references UMS_MENU_RESOURCE
)
/

alter table UMS_CONTROLLER_RESOURCES
	add constraint FKC0BRRL2B6E0JJRAOF3P8DPC36
		foreign key (MENU_ID) references UMS_MENU_RESOURCE
/

create table UMS_CONTROLLER_OPER
(
	ID VARCHAR2(32 char) not null
		primary key,
	CONTROLLER_OPER_NAME VARCHAR2(255 char),
	CONTROLLER_OPER_SN VARCHAR2(255 char),
	INDEX_POS NUMBER(10),
	METHOD_URL_MAPPING VARCHAR2(255 char),
	CONTROLLER_ID VARCHAR2(32 char)
		constraint FKI455415MBF3G8KEX4CETENTHL
			references UMS_CONTROLLER_RESOURCES
)
/

create table UMS_ORG
(
	ID VARCHAR2(32 char) not null
		primary key,
	ADDRESS VARCHAR2(255 char),
	ATT1 VARCHAR2(255 char),
	ATT2 VARCHAR2(255 char),
	ATT3 VARCHAR2(255 char),
	ATT4 VARCHAR2(255 char),
	ATT5 VARCHAR2(255 char),
	ATT6 VARCHAR2(255 char),
	IS_AVAILABLE NUMBER(5),
	MANAGER_TYPE NUMBER(5),
	NAME VARCHAR2(255 char),
	ORDER_NUM NUMBER(10),
	PHONE VARCHAR2(255 char),
	TYPE_ID VARCHAR2(255 char),
	TYPE_NAME VARCHAR2(255 char),
	PID VARCHAR2(32 char)
		constraint FKTF276YQHIK7Q216RHXN6TU21C
			references UMS_ORG,
	PARENT RAW(255),
	PARENT_ID VARCHAR2(32 char)
		constraint FK2N11UKUN27YURNYYRJIDOTUQ
			references UMS_ORG
)
/

create table UMS_USER_ORG_POS
(
	ID VARCHAR2(32) not null
		primary key,
	ORGID VARCHAR2(255),
	POSID VARCHAR2(255),
	USERID VARCHAR2(255)
)
/

create table UMS_USER_ORG_RELATION
(
	ID VARCHAR2(32) not null
		constraint UMS_USER_ORG_RELATION_PK
			primary key,
	ORG_ID VARCHAR2(32)
		constraint FK8XCJGAGL7F32YSHJJX1QQNNU7
			references UMS_ORG,
	USER_ID VARCHAR2(32)
		constraint FK4U433AJYRX68FB5H1A0SW7O30
			references UMS_USER
)
/

create table UMS_USER_POSITION_RELATION
(
	ID VARCHAR2(32) not null
		constraint UMS_USER_POSITION_RELATION_PK
			primary key,
	POSITION_ID VARCHAR2(32)
		constraint FK5Y9TNMW20TG0WBE4KL6DEDU08
			references UMS_POSITION,
	USER_ID VARCHAR2(32)
		constraint FKD6WLG7NKUVQ4965GGTQNXIXY2
			references UMS_USER
)
/

create table UMS_DEPARTMENT_RELATION
(
	ID VARCHAR2(32) not null
		primary key,
	DEPARTMENT_ID VARCHAR2(255),
	USER_ID VARCHAR2(255)
)
/

create table UMS_USER_ROLE
(
	ID VARCHAR2(32) not null
		primary key,
	ROLE_ID VARCHAR2(255),
	USER_ID VARCHAR2(255)
)
/

create table UMS_ORG_ROLE
(
	ID VARCHAR2(32) not null
		constraint UMS_ORG_ROLE_PK
			primary key,
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(50),
	SN VARCHAR2(50),
	ORG_ID VARCHAR2(32)
)
/

create table UMS_USER_ORG_ROLE_RELATION
(
	ID VARCHAR2(32) not null
		constraint UMS_USER_ORG_ROLE_RELATION_PK
			primary key,
	ROLE_ID VARCHAR2(32)
		constraint FKFASCI6JQN9VUA6NKBKHP8GWBX
			references UMS_ORG_ROLE,
	USER_ID VARCHAR2(32)
		constraint FKDOBQRNS9ID6PGYOFTNREI65KT
			references UMS_USER
)
/

create table UMS_DICTIONARY_ITEM
(
	ID VARCHAR2(36) not null
		constraint UMS_DICTIONARY_ITEM_PK
			primary key,
	CODE VARCHAR2(255),
	VALUE VARCHAR2(20),
	IS_AVAILABLE NUMBER(1),
	SERIAL NUMBER,
	TYPE_ID VARCHAR2(36)
)
/

create table UMS_DICTIONARY_TYPE
(
	ID VARCHAR2(36) not null
		constraint UMS_DICTIONARY_TYPE_PK
			primary key,
	CODE VARCHAR2(255),
	VALUE VARCHAR2(255),
	IS_AVAILABLE NUMBER(1),
	DESCRIPTION VARCHAR2(255)
)
/

alter table UMS_DICTIONARY_ITEM
	add constraint FKMM3EUVJSCQVWC2A8G96VNXPBS
		foreign key (TYPE_ID) references UMS_DICTIONARY_TYPE
/

create table UMS_LOG
(
	ID VARCHAR2(32) not null
		primary key,
	APP_SN VARCHAR2(255),
	BACK_END_ACCESS_PATH VARCHAR2(255),
	BROWSER VARCHAR2(255),
	EXEC_TIME NUMBER(19),
	FRONT_END_ACCESS_PATH VARCHAR2(255),
	IP VARCHAR2(255),
	LOG_LEVEL NUMBER(5),
	LOG_TYPE NUMBER(5),
	OP_DESC VARCHAR2(255),
	OP_RESOURCE VARCHAR2(255),
	OP_RESULT NUMBER(5),
	OP_SYSTEM VARCHAR2(255),
	OP_TIME DATE,
	OP_TYPE NUMBER(5),
	USERNAME VARCHAR2(255)
)
/

create table UMS_GROUP
(
	ID VARCHAR2(32) not null
		primary key,
	DESCRIPTION VARCHAR2(255),
	IS_AVAILABLE NUMBER(5),
	NAME VARCHAR2(255),
	ORG_ID VARCHAR2(255)
)
/

create table UMS_USER_GROUP_RELATION
(
	ID VARCHAR2(32) not null
		primary key,
	GROUP_ID VARCHAR2(32),
	USER_ID VARCHAR2(32)
)
/

create table UMS_USER_ORG_GROUP_POS
(
	ID VARCHAR2(32) not null
		primary key,
	GROUPID VARCHAR2(255),
	ORGID VARCHAR2(255),
	POSID VARCHAR2(255),
	USERID VARCHAR2(255)
)
/

